// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/AddChatRoomMember": {
            "post": {
                "summary": "增加群成员(40人以内)",
                "parameters": [
                    {
                        "description": "ToWxids 多个微信ID用,隔开 QID 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.AddChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/AddContactLabel": {
            "post": {
                "summary": "添加标签",
                "parameters": [
                    {
                        "description": "添加标签",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Label.AddParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/AutoAuth": {
            "post": {
                "summary": "二次登陆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/Awaken": {
            "post": {
                "summary": "唤醒登陆(只限扫码登录)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/BindMobile": {
            "post": {
                "parameters": [
                    {
                        "description": "Opcode: 1:获取验证码 2:绑定手机号 3:解绑手机号",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.BindMobileRequestParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/CheckLoginQrcode": {
            "post": {
                "summary": "检测二维码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入取码时返回的UUID",
                        "name": "uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/CreateChatRoom": {
            "post": {
                "summary": "创建群聊",
                "parameters": [
                    {
                        "description": "ToWxids 多个微信ID用,隔开 至少三个好友微信ID以上",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.CreateChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DelChatRoomMember": {
            "post": {
                "summary": "删除群成员",
                "parameters": [
                    {
                        "description": "ToWxids:多个微信ID用,隔开 QID: 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.AddChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DelFavItem": {
            "post": {
                "summary": "删除收藏",
                "parameters": [
                    {
                        "description": "FavId在同步收藏中获取",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Favor.DelParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DelFriend": {
            "post": {
                "summary": "删除好友",
                "parameters": [
                    {
                        "description": "UserName: 要删除的好友wxid",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.DelFriendParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DelSafetyInfo": {
            "post": {
                "parameters": [
                    {
                        "description": "输入登录成功后的wxid",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.DelSafeDeviceParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DeleteContactLabel": {
            "post": {
                "summary": "删除标签",
                "parameters": [
                    {
                        "description": "删除标签",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Label.DeleteParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DeleteFromContact": {
            "post": {
                "summary": "移出通讯录",
                "parameters": [
                    {
                        "description": "PhoneNumberList:要删除的手机号 Mobile:自己的手机号",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.UploadParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/DownloadVoice": {
            "post": {
                "parameters": [
                    {
                        "description": "同步消息获取参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.DownloadVoiceParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/FavSync": {
            "post": {
                "summary": "同步收藏",
                "parameters": [
                    {
                        "description": "keybuf:第二次请求需需带上第一次返回的",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Favor.SyncParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/Get62Data": {
            "post": {
                "summary": "获取62数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetA8Key": {
            "post": {
                "parameters": [
                    {
                        "description": "OpCode = 2 Scene = 4 CodeType = 19 CodeVersion = 5 为默认参数,如有需求自行修改",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.GetA8KeyParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetBillList": {
            "post": {
                "parameters": [
                    {
                        "description": "输入登录成功后的wxid",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.DelSafeDeviceParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetCacheInfo": {
            "post": {
                "summary": "获取登陆缓存信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetChatRoomInfo": {
            "post": {
                "summary": "获取群详情(不带公告内容)",
                "parameters": [
                    {
                        "description": "UserNameList == 群ID,多个查询请用,隔开",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.GetChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetChatRoomInfoDetail": {
            "post": {
                "summary": "获取群信息(带公告内容)",
                "parameters": [
                    {
                        "description": "QID == 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.GetChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetChatRoomMemberDetail": {
            "post": {
                "summary": "获取群成员详情",
                "parameters": [
                    {
                        "description": "QID = 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.GetChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetContact": {
            "post": {
                "summary": "获取通讯录好友详情",
                "parameters": [
                    {
                        "description": "Towxids 要获取的微信(最多20个,建议15个), ChatRoom查询群里成员以外留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.GetContactDetailparameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetContactLabelList": {
            "post": {
                "summary": "获取标签列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "微信id",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetContactList": {
            "post": {
                "summary": "获取通讯录好友",
                "parameters": [
                    {
                        "description": "CurrentWxcontactSeq和CurrentChatRoomContactSeq没有的情况下填写0",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.GetContactListparameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetContactStatus": {
            "post": {
                "summary": "获取好友是否删除拉黑自己",
                "parameters": [
                    {
                        "description": "1:正常 0:删除 -1:拉黑",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.GetContactStatusParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetFavInfo": {
            "post": {
                "summary": "获取收藏信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wxid:账号的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetFavItem": {
            "post": {
                "summary": "读取收藏内容",
                "parameters": [
                    {
                        "description": "FavId在同步收藏中获取",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Favor.GetFavItemParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetLoginQrcode": {
            "post": {
                "summary": "获取登录二维码",
                "parameters": [
                    {
                        "description": "不使用代理留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Login.GetQRReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetMFriend": {
            "post": {
                "summary": "获取通讯录好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "微信ID",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetProfile": {
            "post": {
                "summary": "取个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆后的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetQrcode": {
            "post": {
                "parameters": [
                    {
                        "description": "非获取群聊二维码时Chatroom字段留空 style:二维码样式 0-2",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.GetQrRequestParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/GetSafetyInfo": {
            "post": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "输入登录成功后的wxid",
                        "name": "body",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/HeartBeat": {
            "post": {
                "summary": "心跳",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/InviteChatRoomMember": {
            "post": {
                "summary": "邀请群成员(40人以上)",
                "parameters": [
                    {
                        "description": "ToWxids 多个微信ID用,隔开 QID: 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.AddChatRoomParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/LogOut": {
            "post": {
                "summary": "退出登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/MPGetA8Key": {
            "post": {
                "parameters": [
                    {
                        "description": "scene 2=好友或群 3=历史阅读 4=二维码 7=公众号 30=扫码进群 opcode=2",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.MPGetA8KeyParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/Manualauth": {
            "post": {
                "summary": "账号密码登陆",
                "parameters": [
                    {
                        "description": "不使用代理留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Login.ManualAuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/MassSend": {
            "post": {
                "summary": "群发助手",
                "parameters": [
                    {
                        "description": "ToWxids: 群发对象的wxid，用;分割组成一个字符串 Content:文本内容 Type: 1=文字消息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.MassSendRequestParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/MoveToContract": {
            "post": {
                "summary": "保存到通讯录",
                "parameters": [
                    {
                        "description": "Val = 1添加 0移除",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.MoveContractListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/NewSync": {
            "post": {
                "summary": "同步消息",
                "parameters": [
                    {
                        "description": "Scene填写0, Synckey留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SyncParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/Newinit": {
            "post": {
                "summary": "初次登录初始化",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请输入登陆成功的wxid",
                        "name": "wxid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "二次同步需要带入",
                        "name": "MaxSynckey",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "二次同步需要带入",
                        "name": "CurrentSynckey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/OperateChatRoomAdmin": {
            "post": {
                "summary": "群管理操作(添加、删除、转让)",
                "parameters": [
                    {
                        "description": "ToWxids = 多个wxid用,隔开(仅限于添加/删除管理员) Val = 1添加 2删除 3转让",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.OperateChatRoomAdminParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/QuitChatroom": {
            "post": {
                "summary": "退出群聊",
                "parameters": [
                    {
                        "description": "QID = 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.QuitGroupParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/RevokeMsg": {
            "post": {
                "summary": "撤回消息",
                "parameters": [
                    {
                        "description": "记录之前发送的消息的id与时间进行撤销",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.RevokeMsgParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ScanIntoGroup": {
            "post": {
                "summary": "扫码进群",
                "parameters": [
                    {
                        "description": "url",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.ScanIntoGroupParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SearchContact": {
            "post": {
                "summary": "搜索联系人",
                "parameters": [
                    {
                        "description": "默认填写FromScene=0,SearchScene=1",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.SearchParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SendAppMsg": {
            "post": {
                "summary": "发送App消息",
                "parameters": [
                    {
                        "description": "Type请根据场景设置, Content请自行构造",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SendAppMsgParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SendImg": {
            "post": {
                "summary": "发送图片",
                "parameters": [
                    {
                        "description": "base64为图片base64编码后数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SendImageMsgParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SendMsg": {
            "post": {
                "summary": "发送文本消息",
                "parameters": [
                    {
                        "description": "Type请填写1",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SendNewMsgParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SendVideo": {
            "post": {
                "summary": "发送视频",
                "parameters": [
                    {
                        "description": "Video:视频Base64 Image:封面Base64 VideoTime:视频长度",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SendVideoMsgParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SendVoice": {
            "post": {
                "summary": "发送语音",
                "parameters": [
                    {
                        "description": "Type： AMR = 0, MP3 = 2, SILK = 4, SPEEX = 1, WAVE = 3 VoiceTime ：音频长度 1000为一秒",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.SendVoiceMessageParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetChatRoomAnnouncement": {
            "post": {
                "summary": "设置群公告",
                "parameters": [
                    {
                        "description": "Content = 公告内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.OperateChatRoomInfoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetChatRoomName": {
            "post": {
                "summary": "设置群名称",
                "parameters": [
                    {
                        "description": "Content = 名称",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.OperateChatRoomInfoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetChatRoomRemarks": {
            "post": {
                "summary": "设置群备注(仅自己可见)",
                "parameters": [
                    {
                        "description": "QID = 群ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Group.OperateChatRoomInfoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetContactBlacklist": {
            "post": {
                "summary": "添加/移除黑名单",
                "parameters": [
                    {
                        "description": "Enable: 0 移出黑名单 1 移入黑名单",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.BlacklistParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetContactRemarks": {
            "post": {
                "summary": "设置好友备注",
                "parameters": [
                    {
                        "description": "设置好友备注",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.SetRemarksParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetPassword": {
            "post": {
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "Ticket从VerifyPassword获取",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.NewSetPasswdParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SetSnsViewTime": {
            "post": {
                "summary": "朋友圈权限设置",
                "parameters": [
                    {
                        "description": "调用参数请联系",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.PrivacySettingsParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ShareCard": {
            "post": {
                "summary": "分享名片",
                "parameters": [
                    {
                        "description": "ToWxid=接收的微信ID Id=名片wxid NickName=名片昵称 Alias=名片别名 ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.ShareCardParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ShareLocation": {
            "post": {
                "summary": "分享位置",
                "parameters": [
                    {
                        "description": "x=经度 y=纬度 scale=地图缩放倍数，可填10，100实验",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Msg.ShareLocationParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsComment": {
            "post": {
                "summary": "朋友圈点赞/评论",
                "parameters": [
                    {
                        "description": "type：1点赞 2：文本 3:消息 4：with 5陌生人点赞 replyCommnetId：回复评论Id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.CommentParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsObjectDetail": {
            "post": {
                "summary": "获取特定一条朋友圈详情内容",
                "parameters": [
                    {
                        "description": "Id为对象朋友圈内容的id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.GetIdDetailParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsObjectTop": {
            "post": {
                "summary": "朋友圈操作",
                "parameters": [
                    {
                        "description": "type：1删除朋友圈2设为隐私3设为公开4删除评论5取消点赞",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.OperationParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsPost": {
            "post": {
                "summary": "发布朋友圈",
                "parameters": [
                    {
                        "description": "请自行构造xml内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.Messagearameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsSync": {
            "post": {
                "summary": "同步朋友圈",
                "parameters": [
                    {
                        "description": "Synckey可留空",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.MmSnsSyncParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsTimeline": {
            "post": {
                "summary": "朋友圈首页列表",
                "parameters": [
                    {
                        "description": "打开首页时：Fristpagemd5留空,Maxid填写0",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.GetListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsUpload": {
            "post": {
                "summary": "朋友圈上传",
                "parameters": [
                    {
                        "description": "支持图片和视频",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.SnsUploadParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/SnsUserPage": {
            "post": {
                "summary": "获取特定人朋友圈",
                "parameters": [
                    {
                        "description": "打开首页时：Fristpagemd5留空,Maxid填写0",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FriendCircle.GetDetailparameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/UpdateContactLabel": {
            "post": {
                "summary": "修改标签",
                "parameters": [
                    {
                        "description": "修改标签",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Label.UpdateNameParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/UpdateContactLabelList": {
            "post": {
                "summary": "更新标签列表",
                "parameters": [
                    {
                        "description": "ToWxids: 要更新label的对象wxid",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Label.UpdateListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/UpdateProfile": {
            "post": {
                "summary": "修改个人信息",
                "parameters": [
                    {
                        "description": "NickName=昵称  Sex=性别（0:位置 1:男 2：女） Country=国家 Province=省份 City=城市 Signature=个性签名",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.UpdateProfileParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/UploadHeadImage": {
            "post": {
                "summary": "修改头像",
                "parameters": [
                    {
                        "description": "修改头像",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.UploadHeadImageParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/UploadMContact": {
            "post": {
                "summary": "上传通讯录",
                "parameters": [
                    {
                        "description": "PhoneNumberList:要上传的手机号 Mobile:自己的手机号",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.UploadParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/VerifyPassword": {
            "post": {
                "summary": "验证密码",
                "parameters": [
                    {
                        "description": "调用SetPassword前调用该接口",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.NewVerifyPasswdParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/VerifySwitch": {
            "post": {
                "summary": "隐私设置",
                "parameters": [
                    {
                        "description": "调用参数请咨询",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.PrivacySettingsParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/VerifyUser": {
            "post": {
                "summary": "发送好友请求",
                "parameters": [
                    {
                        "description": "Scene:来源, VerifyContent: 招呼消息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Friend.SendRequestParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/setProxy": {
            "post": {
                "parameters": [
                    {
                        "description": "删除代理ip时直接留空即可",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tools.SetProxyParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "Favor.DelParam": {
            "type": "object",
            "properties": {
                "favId": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Favor.GetFavItemParam": {
            "type": "object",
            "properties": {
                "favId": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Favor.SyncParam": {
            "type": "object",
            "properties": {
                "keybuf": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.BlacklistParam": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "integer"
                },
                "toWxids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.DelFriendParam": {
            "type": "object",
            "properties": {
                "userName": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.GetContactDetailparameter": {
            "type": "object",
            "properties": {
                "chatRoom": {
                    "type": "string"
                },
                "towxids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.GetContactListparameter": {
            "type": "object",
            "properties": {
                "currentChatRoomContactSeq": {
                    "type": "integer"
                },
                "currentWxcontactSeq": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.GetContactStatusParameter": {
            "type": "object",
            "properties": {
                "userList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.SearchParam": {
            "type": "object",
            "properties": {
                "fromScene": {
                    "type": "integer"
                },
                "searchScene": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.SendRequestParam": {
            "type": "object",
            "properties": {
                "opcode": {
                    "type": "integer"
                },
                "scene": {
                    "type": "integer"
                },
                "v1": {
                    "type": "string"
                },
                "v4": {
                    "type": "string"
                },
                "verifyContent": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.SetRemarksParam": {
            "type": "object",
            "properties": {
                "remarks": {
                    "type": "string"
                },
                "toWxids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Friend.UploadParam": {
            "type": "object",
            "properties": {
                "mobile": {
                    "type": "string"
                },
                "phoneNumberList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.CommentParam": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "replyCommnetId": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.GetDetailparameter": {
            "type": "object",
            "properties": {
                "fristpagemd5": {
                    "type": "string"
                },
                "maxid": {
                    "type": "integer"
                },
                "towxid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.GetIdDetailParam": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "towxid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.GetListParam": {
            "type": "object",
            "properties": {
                "fristpagemd5": {
                    "type": "string"
                },
                "maxid": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.Messagearameter": {
            "type": "object",
            "properties": {
                "blackList": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "withUserList": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.MmSnsSyncParam": {
            "type": "object",
            "properties": {
                "synckey": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.OperationParam": {
            "type": "object",
            "properties": {
                "commnetId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.PrivacySettingsParam": {
            "type": "object",
            "properties": {
                "function": {
                    "type": "integer"
                },
                "value": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "FriendCircle.SnsUploadParam": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.AddChatRoomParam": {
            "type": "object",
            "properties": {
                "qid": {
                    "type": "string"
                },
                "toWxids": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.CreateChatRoomParam": {
            "type": "object",
            "properties": {
                "toWxids": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.GetChatRoomParam": {
            "type": "object",
            "properties": {
                "qid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.MoveContractListParam": {
            "type": "object",
            "properties": {
                "qid": {
                    "type": "string"
                },
                "val": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.OperateChatRoomAdminParam": {
            "type": "object",
            "properties": {
                "qid": {
                    "type": "string"
                },
                "toWxids": {
                    "type": "string"
                },
                "val": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.OperateChatRoomInfoParam": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "qid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.QuitGroupParam": {
            "type": "object",
            "properties": {
                "qid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Group.ScanIntoGroupParam": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Label.AddParam": {
            "type": "object",
            "properties": {
                "labelName": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Label.DeleteParam": {
            "type": "object",
            "properties": {
                "labelID": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Label.UpdateListParam": {
            "type": "object",
            "properties": {
                "labelID": {
                    "type": "string"
                },
                "toWxids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Label.UpdateNameParam": {
            "type": "object",
            "properties": {
                "labelID": {
                    "type": "integer"
                },
                "newName": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Login.GetQRReq": {
            "type": "object",
            "properties": {
                "deviceID": {
                    "type": "string"
                },
                "deviceName": {
                    "type": "string"
                },
                "proxy": {
                    "$ref": "#/definitions/models.ProxyInfo"
                }
            }
        },
        "Login.ManualAuthReq": {
            "type": "object",
            "properties": {
                "androidBaseBand": {
                    "type": "string"
                },
                "androidBuild": {
                    "type": "string"
                },
                "androidDevice": {
                    "type": "string"
                },
                "androidID": {
                    "type": "string"
                },
                "androidOstype": {
                    "type": "string"
                },
                "deviceData": {
                    "type": "string"
                },
                "iccid": {
                    "type": "string"
                },
                "imsi": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phoneSerial": {
                    "type": "string"
                },
                "proxy": {
                    "$ref": "#/definitions/models.ProxyInfo"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "Msg.MassSendRequestParam": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "toWxids": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.RevokeMsgParam": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "integer"
                },
                "msgId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.SendAppMsgParam": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.SendImageMsgParam": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.SendNewMsgParam": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.SendVideoMsgParam": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "video": {
                    "type": "string"
                },
                "videoTime": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.SendVoiceMessageParam": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "voiceTime": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.ShareCardParam": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Msg.ShareLocationParam": {
            "type": "object",
            "properties": {
                "poiname": {
                    "type": "string"
                },
                "scale": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "toWxid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "Msg.SyncParam": {
            "type": "object",
            "properties": {
                "scene": {
                    "type": "integer"
                },
                "synckey": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.BindMobileRequestParam": {
            "type": "object",
            "properties": {
                "opcode": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "verifyCode": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.DelSafeDeviceParam": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.DownloadVoiceParam": {
            "type": "object",
            "properties": {
                "bufid": {
                    "type": "string"
                },
                "fromUserName": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "newMsgId": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.GetA8KeyParam": {
            "type": "object",
            "properties": {
                "codeType": {
                    "type": "integer"
                },
                "codeVersion": {
                    "type": "integer"
                },
                "opCode": {
                    "type": "integer"
                },
                "scene": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.GetQrRequestParam": {
            "type": "object",
            "properties": {
                "chatroom": {
                    "type": "string"
                },
                "style": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.MPGetA8KeyParam": {
            "type": "object",
            "properties": {
                "codeType": {
                    "type": "integer"
                },
                "codeVersion": {
                    "type": "integer"
                },
                "opCode": {
                    "type": "integer"
                },
                "scene": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "Tools.SetProxyParam": {
            "type": "object",
            "properties": {
                "proxy": {
                    "$ref": "#/definitions/models.ProxyInfo"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "User.NewSetPasswdParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "ticket": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "User.NewVerifyPasswdParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "User.PrivacySettingsParam": {
            "type": "object",
            "properties": {
                "function": {
                    "type": "integer"
                },
                "value": {
                    "type": "integer"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "User.UpdateProfileParam": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sex": {
                    "type": "integer"
                },
                "signature": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "User.UploadHeadImageParam": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "wxid": {
                    "type": "string"
                }
            }
        },
        "models.ProxyInfo": {
            "type": "object",
            "properties": {
                "proxyIp": {
                    "type": "string"
                },
                "proxyPassword": {
                    "type": "string"
                },
                "proxyUser": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
